<<<<<<< HEAD
type: system-logs
id: system-syslog

{{ if .use_journald }}
use_journald: true
=======
type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
>>>>>>> 00d7161a1d (Revert system module support for journald (#41489))
{{ end }}
exclude_files: [".gz$"]
multiline:
  pattern: "^\\s"
  match: after
processors:
  - add_locale: ~
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.12.0
