<<<<<<< HEAD
type: system-logs
id: system-auth

{{ if .use_journald }}
use_journald: true
=======
type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
>>>>>>> 00d7161a1d (Revert system module support for journald (#41489))
{{ end }}
exclude_files: [".gz$"]

multiline:
  pattern: "^\\s"
  match: after

processors:
  - add_locale: ~

tags: {{ .tags | tojson }}

publisher_pipeline.disable_host: {{ inList .tags "forwarded" }}
